apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fizz-buzz-operator.fullname" . }}
  labels:
    {{- include "fizz-buzz-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fizz-buzz-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "fizz-buzz-operator.pod.annotations" . | nindent 8 }}
      labels:
        {{- include "fizz-buzz-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fizz-buzz-operator.serviceAccountName" . }}
      {{- if .Values.useUserNamespaces }}
      hostUsers: true
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (concat .Values.podEnvs .Values.defaultEnvs) | uniq }}
          env:
              {{- toYaml . | nindent 12}}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.podContainerPort }}
              protocol: TCP
            - name: status
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: status
          readinessProbe:
            httpGet:
              path: /healthz
              port: status
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 10 }}
      {{- end }}
