{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "fizz-buzz-operator.labels" . | nindent 4 }}
  name: {{ include "fizz-buzz-operator.fullname" . }}
rules:
  - apiGroups:
      - fizz-buzz.hegerdes.com
    resources:
      - instances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - fizz-buzz.hegerdes.com
    resources:
      - instances/status
    verbs:
      - get
  - apiGroups:
      - fizz-buzz.hegerdes.com
    resources:
      - instances
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - fizz-buzz.hegerdes.com
    resources:
      - instances/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fizz-buzz-operator.fullname" . }}
  labels:
    {{- include "fizz-buzz-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fizz-buzz-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "fizz-buzz-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
