apiVersion: v1
kind: Service
metadata:
  name: {{ include "fizz-buzz-operator.fullname" . }}
  labels:
    {{- include "fizz-buzz-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "fizz-buzz-operator.selectorLabels" . | nindent 4 }}
