apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fizz-buzz-operator
  name: fizz-buzz-operator-instance-viewer-role
rules:
- apiGroups:
  - fizz-buzz.hegerdes.com
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fizz-buzz.hegerdes.com
  resources:
  - instances/status
  verbs:
  - get
