apiVersion: fizz-buzz.hegerdes.com/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: fizz-buzz-operator
    app.kubernetes.io/managed-by: kustomize
  name: instance-sample
spec:
  # TODO(user): Add fields here
