name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write
  attestations: write

env:
  GO_VERSION: ^1.23

jobs:
  docker-release:
    uses: hegerdes/helper-suite/.github/workflows/reusable-docker-build.yml@main
    with:
      build-name: ${{ github.repository_owner }}/fizz-buzz-operator,ghcr.io/${{ github.repository_owner }}/fizz-buzz-operator
      build-tags: ${{ github.ref_name }},latest
      sign-with-github: true
      build-args: |
        COMMIT_HASH=${{ github.sha }}
        COMMIT_TAG=${{ github.ref_name }}
      build-labels: MAINTAINER=${{ github.repository_owner }}
      build-platforms: linux/amd64,linux/arm64
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKERHUB_TOKEN }}

  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Package Charts
        run: |
          # Package charts
          mkdir -p charts/.ci-build
          echo "Setting chart version to ${{ github.ref_name }} and app version to ${{ github.ref_name }}"
          helm dependency update charts/fizz-buzz-operator
          helm package charts/fizz-buzz-operator --version ${{ github.ref_name }} --app-version ${{ github.ref_name }} --destination charts/.ci-build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
