name: Test-Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HELM_DOCS_VERSION: 1.14.2
  GO_VERSION: ^1.23

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Run Build
        run: make

      # - name: Run Lint
      #   run: make lint

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Run Tests
        run: make test

  helm-chart-test:
    uses: hegerdes/helper-suite/.github/workflows/reusable-helm-package.yml@main
    with:
      chart-sources-dir: charts/fizz-buzz-operator
      chart-test-config-dir: charts
      chart-publish: false
      chart-release-version: "0.1.0"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Install helm plugins
        run: |
          helm plugin install https://github.com/losisin/helm-values-schema-json.git
          curl -sL --output helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v${{ env.HELM_DOCS_VERSION }}/helm-docs_${{ env.HELM_DOCS_VERSION }}_Linux_x86_64.tar.gz
          tar -xzvf helm-docs.tar.gz -C /usr/local/bin

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
